title: Jieun Lee
subtitle: Web Develop student
description: >- # this means to ignore newlines until "baseurl:"
  devlopr-jekyll is a Jekyll Theme Built For Developers

url: "https://jieun-tech.github.io" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: Blog
      url: /blog
#    - text: Shop
#      url : /shop/
    - text: About Me
      url: /about
    - text: Contact Me
      url : /contact
#    - text: Styleguide
#      url: /styleguide/
    

# Edit these details 

author_logo: profile.png
author: Jieun Lee
author_bio: 안녕하세요. 웹개발자를 꿈꾸는 학생입니다.
author_email: "jieun.tech@gmail.com"
author_location: Korea
author_website_url: "https://jieun-tech.github.io"

#author_work_experiences: 
#            - company_name: Google
#              company_logo: google.png
#              company_url: https://google.com
#              designation: Software Engineer
#              description: Worked on various Google Products
#              visibility: true
#            - company_name: Microsoft
#              company_logo: microsoft.png
#              company_url: https://microsoft.com
#              designation: Azure Developer
#              description: Worked on various Azure Cloud Products
#              visibility: true

author_education_details:
              - college_logo: mit.png
                college_name: 한경
                college_url: https://mit.org
                college_degree: CS Engineer
                description: Bachelor of Technology
                visibility: true

author_project_details:
              - project_thumbnail: gamershub.png
                project_title: Gamers Hub
                project_description: A Platform built for Gamers and Game Devs
                project_url: https://gamershub.in
                visibility: true
              - project_thumbnail: programmingebooks.png
                project_title: Programming Ebooks
                project_description: A Platform to easily find and read programming books
                project_url: https://programmingebooks.com
                visibility: true

# social links
#twitter_username: johndoe
github_username:  jieun-tech
#facebook_username: johndoe
#linkedin_username: johndoe
#behance_username: johndoe
#instagram_username: johndoe
#medium_username: johndoe
#telegram_username: johndoe
#dribbble_username: johndoe
#flickr_username: johndoe

#for comments using disqus
disqus_shortname: jieun-tech

# wakatime username (coding activity)
wakatime_username: jieun-tech

# formspree (contact form)
formspree_email: jieun.tech@gmail.com

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# google analytics
google_analytics: UA-46783401-10 

# Choose what to show ( can be true or false)
show_author_work_experiences: false
show_author_education_details: true
show_author_project_details: true

# dont touch this unless required
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-algolia
# - jekyll-archives

# algolia search 
algolia:
  application_id: D9WA1YKTRQ
  index_name: blog_posts # You can replace that with whatever name you want
  files_to_exclude: []
  nodes_to_index: 'article'
  search_only_api_key: 58ffdd7cd6c45ec1577a7fcd789b1b9a

# pagination of posts
paginate: 8
per_page: 4
paginate_path: "/blog/page/:num/"

# minify 
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'


collections:
 - products

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/